import 'package:email_validator/email_validator.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:merkha_app/bloc/page_bloc.dart';
import 'package:flutter/material.dart';
import 'package:merkha_app/shared/shared.dart';
import 'file:///D:/Developer/merkha_app/lib/view/pages/tab/wishlist_tab.dart';
import 'tab/main_tab.dart';
import 'tab/feed_tab.dart';
import 'tab/cart_tab.dart';
import 'tab/profile_tab.dart';

part 'wrapper.dart';
part 'sign_in_page.dart';
part 'main_page.dart';
part 'login_signup_page.dart';
part 'sign_up_1.dart';
part 'sign_up_2.dart';
part 'sign_up_3.dart';