import 'dart:convert';

import 'package:email_validator/email_validator.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:merkha_app/bloc/page_bloc.dart';
import 'package:flutter/material.dart';
import 'package:merkha_app/cubit/cubit.dart';
import 'package:merkha_app/models/models.dart';
import 'package:merkha_app/services/services.dart';
import 'package:merkha_app/shared/shared.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter_greetings/flutter_greetings.dart';
import 'package:merkha_app/view/widgets/widgets.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;
import 'package:smart_select/smart_select.dart';
import 'package:async/async.dart';

part 'wrapper.dart';
part 'sign_in_page.dart';
part 'main_page.dart';
part 'sign_in_option_page.dart';
part 'sign_up_1.dart';
part 'sign_up_2.dart';
part 'sign_up_3.dart';
part 'sign_up_4.dart';
part 'tab_cart.dart';
part 'tab_profile.dart';
part 'tab_feed.dart';
part 'tab_main.dart';
part 'tab_wishlist.dart';
